# Global configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# Rule files
rule_files:
  - "rules/alerts.yml"
  - "rules/recording.yml"

# Scrape configurations
scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape AImpact backend services
  - job_name: 'aimpact-backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'api'
      - targets: ['localhost:8001']
        labels:
          service: 'voice-processor'
      - targets: ['localhost:8002']
        labels:
          service: 'workflow-engine'
      - targets: ['localhost:8003']
        labels:
          service: 'agent-orchestrator'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # Cadvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']

